version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/dev/frontend/Dockerfile
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/dev/backend/Dockerfile
    volumes:
      - ../../backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=thinkleap
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"


  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thinkleap
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: