version: '3.8'

services:
  frontend:
    build:
      context: ${PROJECT_ROOT}/frontend
      dockerfile: ${PROJECT_ROOT}/docker/dev/frontend/Dockerfile
    volumes:
      - ${PROJECT_ROOT}/frontend:/app
      - /app/node_modules
      - ${PROJECT_ROOT}/frontend/.env.local:/app/.env.local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard
    depends_on:
      - backend
    networks:
      - thinkleap-net

  backend:
    build:
      context: ${PROJECT_ROOT}/backend
      dockerfile: ${PROJECT_ROOT}/docker/dev/backend/Dockerfile
    volumes:
      - ${PROJECT_ROOT}/backend:/app
      - /app/node_modules
      - ${PROJECT_ROOT}/shared:/shared
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=thinkleap
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://localhost:3000
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - db
      - redis
    networks:
      - thinkleap-net

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - thinkleap-net

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thinkleap
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - thinkleap-net

networks:
  thinkleap-net:
    driver: bridge

volumes:
  postgres-data: