version: '3.8'

services:
  frontend:
    build:
      context: /home/straw/thinkleap/frontend
      dockerfile: /home/straw/thinkleap/docker/dev/frontend/Dockerfile
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: /home/straw/thinkleap/backend
      dockerfile: /home/straw/thinkleap/docker/dev/backend/Dockerfile
    volumes:
      - ../../backend:/app
      - /app/node_modules
      - ../../shared:/shared
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=thinkleap
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  redis:
    ports:
      - "6380:6379"

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thinkleap