version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    networks:
      - thinkleap-network

  backend:
    depends_on:
      - db
      - redis
    networks:
      - thinkleap-network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - thinkleap-network

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - thinkleap-network

volumes:
  postgres_data:
  redis_data:

networks:
  thinkleap-network:
    driver: bridge