version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/prod/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api.thinkleap.org
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - thinkleap-network

  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/prod/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=thinkleap
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - thinkleap-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - thinkleap-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=thinkleap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - thinkleap-network

volumes:
  postgres_data:
  redis_data:

networks:
  thinkleap-network:
    driver: bridge